name: Terraform CI/CD for practice4/vpc

on:
  push:
    paths:
      - 'practice4/vpc/**'
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform in practice4/vpc
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2

    defaults:
      run:
        working-directory: practice4/vpc

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Show Terraform Output
        run: terraform output
